language: node_js
node_js:
    - 10
cache:
    directories:
        - $HOME/.npm
install:
    - yarn install
    - yarn global add codecov
script:
    - yarn run build
    - yarn test --coverage
after_success:
    - codecov --file=coverage/lcov.info --disable=search,gcov
