jobs:
  include:
    - stage: tests
      language: node_js
      node_js: '10'
      cache: yarn
      install:
        - yarn install
        - yarn global add codecov
      script:
        - yarn run build
        - yarn test --coverage
      after_success:
        - codecov --file=coverage/lcov.info --disable=search,gcov

    - stage: npm release
      language: node_js
      if: tag IS present
      node_js: '10'
      script: yarn build
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_TOKEN'
        skip_cleanup: true
        on:
          tags: true
