language: node_js
node_js:
    - 10
cache:
    directories:
        - $HOME/.npm
install:
    - yarn install
    - yarn global add codecov
script:
    - yarn run build
    - yarn test --coverage
after_success:
    - codecov --file=coverage/lcov.info --disable=search,gcov

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "10"
      script: yarn build
      before_deploy:
        - cd build
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true